version: '3'

services:
  web:
    image: php:7.0-apache
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1

# docker-compose up
